### PR TITLE
Share and delete

### PR DESCRIPTION
**Pull request by Bibhukiju**
# features added
- user can now share and delete file  on longpress
-  after completion of  pdf creation user is again navigated back to homepage

### CODE REVIEW

**Comment by cimplesid** [comment]
@Bibhukiju  fix the conflict and push

**Comment by Bibhukiju** [comment]
> @Bibhukiju fix the conflict and push

dai solve bhayo conflict

**Comment by cimplesid** [comment]
either include #32  in title or description or remove it from the code

**Comment by cimplesid** [comment]
@Bibhukiju also adapt with get and check for new conflicts too

**Comment by cimplesid** [comment]
reopen if required i think another one contains this

**Pull request closed without merging**
